# Generated by Django 4.1.3 on 2022-12-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_theme_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
