# Generated by Django 4.1.3 on 2022-12-05 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_anthology_last_modified_book_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='contents',
            field=models.TextField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_type', models.CharField(max_length=20)),
                ('ideas', models.CharField(max_length=60)),
                ('themes', models.CharField(max_length=60)),
                ('books', models.CharField(max_length=60)),
                ('characters', models.CharField(max_length=60)),
                ('chapters', models.CharField(max_length=60)),
                ('poems', models.CharField(max_length=60)),
                ('series', models.CharField(max_length=60)),
                ('anthologies', models.CharField(max_length=60)),
                ('media', models.CharField(max_length=60)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
