# Generated by Django 4.1.3 on 2022-12-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_compilation_anthologies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilation',
            name='container_id',
            field=models.CharField(default='1', max_length=3),
            preserve_default=False,
        ),
    ]
