# Generated by Django 4.1.3 on 2022-12-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_compilation_container_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='file_path',
        ),
    ]
