# Generated by Django 4.1.3 on 2022-12-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_media_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.IntegerField(choices=[(1, 'Song'), (2, 'Image')], default=1),
        ),
    ]
